services:
    register_walkin_handler:
        class: Derp\Command\RegisterWalkinHandler
        arguments:
            - "@doctrine"
            - "@mailer"
        tags:
            - { name: command_handler, handles: Derp\Command\RegisterWalkin }