services:
    register_walkin_handler:
        class: Derp\Command\RegisterWalkinHandler
        arguments:
            - "@doctrine"
            - "@event_recorder"
        tags:
            - { name: command_handler, handles: Derp\Command\RegisterWalkin }

    when_walkin_registered_notify_triage_nurse:
            class: Derp\Event\WhenWalkinRegisteredNotifyTriageNurse
            arguments:
                - "@mailer"
            tags:
                - { name: event_subscriber, subscribes_to: Derp\Event\WalkinRegistered }
